parameters:
    tables.paypal.amount: %core.table_prefix%paypal_amount

services:
    tas2580.paypal.main:
        class: tas2580\paypal\controller\main
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - %tables.paypal.amount%
    tas2580.paypal.listener:
        class: tas2580\paypal\event\listener
        arguments:
            - @controller.helper
            - @template
            - @user
        tags:
            - { name: event.listener }